### ISSUE TITLE
cannot build..

### ISSUE THREAD

**Issue by TecDroiD** [straga/micropython-esp32-twai#1]
hi, i'd love to use your library implementation. Sadly, it doesn't compile. Seems, I'm missing something. Maybe you can help?

here's my log
[build_can.log](https://github.com/straga/micropython-esp32-twai/files/14755219/build_can.log)

**Comment by oxbown** [comment]
@TecDroiD  https://github.com/micropython/micropython/pull/13763

**Comment by straga** [comment]
Update STATIC -> static
